version: '3'

services:
  reindexer:
    image: reindexer/reindexer:v4.9.0
    ports:
      - "9088:9088"
    volumes:
      - ./reindexer_data:/reindexer_server_data
    environment:
      - REINDEXER_STORAGEPATH=/reindexer_server_data

  go_microservice:
    build: ./micro
    ports:
      - "3000:3000"
    depends_on:
      - reindexer
    environment:
      - REINDEXER.HOST=reindexer
      - REINDEXER.PORT=6534
      - REINDEXER.DATABASE=test
      - REINDEXER.USERNAME=user
      - REINDEXER.PASSWORD=pass
      - APP.HOST=3000
      - APP.TTL=15
      - APP.CLEANUPINTERVAL=30
      - APP.MODE=debug