version: '3'

services:
  reindexer:
    image: reindexer/reindexer:v4.9.0
    ports:
      - "9088:9088"
      - "6534:6534"
    volumes:
      - ./reindexer_data:/reindexer_server_data

  go_microservice:
    build: ./micro
    ports:
      - "8080:8080"
    depends_on:
      - reindexer
    environment:
      - REINDEXER.HOST=localhost
      - REINDEXER.PORT=6534
      - REINDEXER.DATABASE=test
      - REINDEXER.USERNAME=user
      - REINDEXER.PASSWORD=pass
      - APP.HOST=3000